### ISSUE TITLE
Create Contacts link on web build does not work

### ISSUE THREAD

**Issue by eshnil** [gskinnerTeam/flokk#13] opened 2020-07-09 21:36 UTC
![image](https://user-images.githubusercontent.com/51651338/87093164-429a9d00-c22c-11ea-8eea-7cc1c2930cf7.png)

Clicking on "Create Contacts" does nothing. Tested on Flokk.app

**Comment by andyzimmerer** [comment] 2020-08-17 10:12
Thanks

**Comment by cenomla** [comment] 2021-04-15 20:03
Duplicate of https://github.com/gskinnerTeam/flokk/issues/35

**Closed by cenomla** 2021-04-15 20:03 UTC
Labels: duplicate
